services:
  api:
    image: kianbruyenberg/articlesummary-api:latest
    ports:
        - "8090:8080" 
    depends_on:
        - db   
    restart: always
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:8080
        - ConnectionStrings__DefaultConnection=Server=db;port=3306;Database=articlesummary;user=article;password=summary;
  db:
    image: mysql:8.1
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: articlesummary
        MYSQL_USER: article
        MYSQL_PASSWORD: summary
    ports:
        - "3306:3306"
    volumes:
        - dbdata:/var/lib/mysql
  
  watchtower:
    image: containrrr/watchtower
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    command: --interval 60    

volumes: 
  dbdata: