# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET + SonarCloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install SonarScanner
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Install dotnet-coverage
      run: dotnet tool install --global dotnet-coverage

    - name: Begin SonarCloud Analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        dotnet-sonarscanner begin /k:"TheTrumpetist27_ArticleSummaryBackend" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.vscoveragexml.reportsPaths="coverage/coverage.xml"

    - name: Restore dependencies
      run: dotnet restore ./ArticleSummaryBackend.sln

    - name: Build
      run: dotnet build ./ArticleSummaryBackend.sln --no-incremental
    
    - name: Test with coverage
      run: |
        dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"

    - name: End SonarCloud Analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
